### ISSUE TITLE
Grove Pi features

### ISSUE THREAD

**Issue by mpahrens** [LaboratoryForPlayfulComputation/blockytalky#11]
Making this issue to keep track of progress on Grove Pi features. I would love to have some basic blocks for Thursday 7/23. but let me know what you think might be reasonable.

**Comment by bennytheshap** [comment]
MVP: Temp & Humidity, Light, and relay control

**Comment by mpahrens** [comment]
Reminder for checkpoint where we are:
TODO:
- Fix T&H python error
- Fix error handling case where setting to a sensor that is not plugged in
- DSL

**Comment by mpahrens** [comment]
Closing this as it progress up until this point is in master. If any more expansions on GrovePi are to be done, please make a new issue :)
