### ISSUE TITLE
Hardware parameter for get_sensor_type_label_for_id 

### ISSUE THREAD

**Issue by ecokova** [LaboratoryForPlayfulComputation/blockytalky#2]
File: hardware_daemon.ex 
Function: get_sensor_type_label_for_id 
Needs to take in a hw parameter to differentiate and prevent collisions.

**Comment by mpahrens** [comment]
Closing as namespace collisions haven't seemed to be an issue, but we can reopen if we think of a different hardware schema for multiple hardware types.
