### ISSUE TITLE
readme unclear

### ISSUE THREAD

**Issue by bennytheshap** [LaboratoryForPlayfulComputation/blockytalky#34]
Documentations says:
Install brunch io and npm
    cd blockytalky
    rm -rf node_modules
        NOTE: for vagrant, you need to make a symlink to somewhere not shared so that the folder name being too long doesn't crash: mkdir ~/node_modules && ln -s ~/node_modules node_modules
    npm install
    sudo npm install -g brunch

Should this be done inside the VM or on the host system?

**Comment by mpahrens** [comment]
I have updated the readme to be a general landing page, but haven't pushed it to master yet.
I would say, in the meantime, look at these instructions in the wiki and let me know if they make sense:

https://github.com/tufts-LPC/blockytalky_elixir/wiki/Getting-Started-for-Developers

Short answer though, if you are developing using the vagrant VM, then do those steps in the vm. if you are deving (e.g. running the webserver, building) in the host environment, then do those steps in the host environment. npm gets confused if you do both (at least for me with a windows host), so I suggest only picking one.

**Comment by mpahrens** [comment]
I think this is done for the particular issue, but we can open a new ticket with a new ask for changing the readme so that this old information doesn't confuse
