### ISSUE TITLE
Nested callbacks seem broken

### ISSUE THREAD

**Issue by bennytheshap** [LaboratoryForPlayfulComputation/blockytalky#45]
The attached program doesn't do what it should. 

Expected behavior:
Music starts playing at 60bpm
Music will speed up to 240bpm for 4 seconds when a melody message is received
It will stay at 240 as long as a melody message comes again during that time.
Otherwise it will slow back down to 60bpm

Observed behavior:
Music starts playing at 60bpm
Music speeds up to 240bpm when a melody message is received.
But the music never slows back down.

![screen shot 2015-09-03 at 11 14 50 am](https://cloud.githubusercontent.com/assets/122056/9665420/78c5e692-522d-11e5-9b54-c483cb228ea3.png)

**Comment by mpahrens** [comment]
Weird. I'll look into it.

**Comment by mpahrens** [comment]
Fixed, in dev branch, will push to develop to test this week and then stage for next release

**Comment by mpahrens** [comment]
Merged into 0.4.1
