### ISSUE TITLE
Tracking Release Bug

### ISSUE THREAD

**Issue by mpahrens** [LaboratoryForPlayfulComputation/blockytalky#59]
Apply EXRM fixes after getting advice:
https://github.com/bitwalker/exrm/issues/259

**Comment by mpahrens** [comment]
So, an update on this
I spent about 6 hours yesterday trying to:
- revert the version of exrm I was using to one that worked before
- remake the config files, etc.

And what I think it is is that:
- I am building the project with erlang 18 and elixir 1.1
- I am bundling the project with erlang 17 and elixir 0.9
  When it tries to map the conform .conf file onto the schema, and then it runs:
  Code.eval(schema_file), it has a mis match. Don't know why exactly.

So I am building erlang 18 and elixir 1.1 to be bundled this Saturday and see if that fixes everything. If not... then I'll try something else. Because reverting didn't work which makes me think it is environment and not a problem with Paul's exrm or conform libraries.

**Comment by bennytheshap** [comment]
Wow! Thanks for all your efforts. Have Elixir and Erlang changed that much that quickly?

**Comment by mpahrens** [comment]
As discussed, this maaaaaaay be fixed, so once I get a second set of eyes on it we can close this out. Probably once I get an image out Wednesday.

**Comment by mpahrens** [comment]
closing the issue since it seems to be fixed. Will make a new .img with erlang / elixir for dev purposes once I get to school and grab the usb sd card reader/writer after the holiday.
