### ISSUE TITLE
Replace context opt in send message with compile time check

### ISSUE THREAD

**Issue by mpahrens** [LaboratoryForPlayfulComputation/blockytalky#60]
Currently, the blockly transpiler checks if a send message block is:
- in a defmotif
- not
  if it is in a defmotif, then it generates the `send_message('mesage','target',context: :music)` macro, otherwise it generates one with `context: :top` as in top level. 

The reason is that to send a "well timed" message from the defmotif, then the DSL compiler needs to generate Sonic Pi ruby DSL code to send the message from sonic pi at that musical moment to the BT message API, not at the moment the motif is defined (top level).

Instead:
- remove this from the blockly level and remove the option.
- in the defmotif macro, set some compile time macro var (@context) to be music upon beginning and top upon exiting.
- In the send_message macro, check the context from @context, with top being default if none is set. and switch on that instead of a passed in op.

This will turn statements that look like:
<code><pre>
start do
  send_message("hello","walle",context: :top)
end
defmotif "melody" do
  wait_for(:beat1)
  send_message("ping","walle", context: :music)
end
</pre></code>
into 
<code><pre>
start do
  send_message("hello","walle")
end
defmotif "melody" do
  wait_for(:beat1)
  send_message("ping","walle")
end
</pre></code>

**Comment by bennytheshap** [comment]
👍🏿

**Comment by mpahrens** [comment]
Done, in test branch, will test on Pi this week and merge if successful

**Comment by mpahrens** [comment]
merged into 0.4.1 (lang) but I didn't change the code gen (blockly) to remove the opts until I can do some more testing, but it works as expected
