### ISSUE TITLE
Add documentation around code generation (JS -> Elixir)

### ISSUE THREAD

**Issue by rustynymph** [LaboratoryForPlayfulComputation/blockytalky#61]

**Comment by bennytheshap** [comment]
I like this idea! Did you and Matt ever talk?

**Comment by mpahrens** [comment]
Yep! This is a follow up so that what we talked about to fix the issue gets put in formal dev docs for others

**Comment by bennytheshap** [comment]
Awesome!

**Comment by mpahrens** [comment]
Added some preliminary documentation here: 
https://github.com/LaboratoryForPlayfulComputation/blockytalky/wiki/Beginner's-Guide-to-Adding-New-Blocks
It should be enough to keep people out of the woods for now re: Blockly
