### ISSUE TITLE
Dev Documentation re: DSL and UserState (Runtime system)

### ISSUE THREAD

**Issue by mpahrens** [LaboratoryForPlayfulComputation/blockytalky#63]
I think the next developer-oriented documentation I'll do is around the DSL structure and the UserState (Runtime System) genserver.

Truth be told it really could be redesigned better, but it isn't terrible as it is, so I'll document it first and then we can have a discussion around the documentation about whether it is worth it to redo it or not. Mostly just how a "user program" is implemented and handled. I'll start a discussion in base camp later with what I mean.

**Comment by bennytheshap** [comment]
Awesome. Thanks!

**Comment by mpahrens** [comment]
Preliminary documentation is done, there are definitely parts missing, but I'm going to let people open specific tickets for me as needed now that I think it is easier to get started.
